services:
  image: swiftdeploy:latest
  port: 3000
  mode: stable
  version: "1.0.0"
  replicas: 1
  restart: unless-stopped

nginx:
  image: nginx:latest
  port: 8080
  proxy_timeout: 30
  contact: admin@swiftdeploy.local

network:
  name: swiftdeploy-net
  driver_type: bridge

volumes:
  logs:
    name: swiftdeploy-logs
